# OPENCART_PORT=8081 PHPADMIN_PORT=8888 LOCAL_IP=$(hostname -I | grep -o "^[0-9.]*") docker compose up -d

#version: '3'
services:

  phpadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=bn_opencart
    ports:
      - '8888:80'

  mariadb:
    image: docker.io/bitnami/mariadb:11.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    ports:
      - '3306:3306'

  opencart:
    image: docker.io/bitnami/opencart:4
    ports:
      - '8081:8080'
      - '443:8443'
    environment:
      - OPENCART_HOST=127.0.0.1:8081
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'opencart_data:/bitnami/opencart'
      - 'opencart_storage_data:/bitnami/opencart_storage/'
    depends_on:
      - mariadb

  selenoid:
    image: "aerokube/selenoid:latest-release"
    ports:
      - "4444:4444"
    volumes:
      - /c:/Users/1/Docker/ecd93a4bf7666d97d62bcecbe2713e55/selenoid/browsers.jon:/etc/selenoid/browsers.jon
      - type: bind
        source: /c/Users/1/.aerokube/selenoid
        target: /etc/selenoid
      - type: bind
        source: /c/Users/1/.aerokube/selenoid/video
        target: /opt/selenoid/video
      - type: bind
        source: /c/Users/1/.aerokube/selenoid/logs
        target: /opt/selenoid/logs
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir","/opt/selenoid/logs"]
    depends_on:
      - opencart

  selenoid-ui:
    image: "aerokube/selenoid-ui:latest-release"
    links:
      - selenoid
    ports:
      - "8083:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
    depends_on:
     - selenoid

  jenkins:
    image: docker.io/bitnami/jenkins:2
    ports:
      - '8082:8082'
    environment:
      - JENKINS_HTTP_PORT_NUMBER=8082
      - JENKINS_PASSWORD=bitnami
    volumes:
      - 'jenkins_data:/bitnami/jenkins'
    depends_on:
       - selenoid-ui

  tests:
    image: 6ab138ea73fb
    build: .
    depends_on:
      - opencart
      - selenoid
      - selenoid-ui
      - jenkins

volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
  opencart_storage_data:
    driver: local
  jenkins_data:
    driver: local
