[pytest]
addopts = -v 
          -s 
          #--headed
          --screenshot only-on-failure 
          --browser chromium 
          --output test-results 
          --alluredir=allure-results

filterwarnings = error
markers =
    admin_login: admin login
    admin_logout: admin logout
    add_category: add category
    add_product: add product
    add_same_product: add same product

    search: search
    bad_search: bad search
    change_currency: change currency
    add_to_cart: cart

    valid_registration: registration
    invalid_registration: registration

    dog: dog